version: '3.8'

services:
  db-service:
    image: postgres:13
    container_name: db-service
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-chadani_db}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-chadani_pass}
      POSTGRES_USER: ${DB_USER:-chadani_user}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - private-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${DB_USER:-chadani_user}", "-d","${DB_NAME:-chadani_db}", "arg"]
      interval: 20s
      timeout: 10s
      retries: 2

  backend-api: 
    build: .
    container_name: chadani-backend-api
    ports:
    # - host:container
      - "8000:8000"
    environment:
      # These match the ${VAR} names in your application.properties
      - DB_HOST=db-service
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-studentdb}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    # volumes:
    #   - /var/log:/var/log
    #   - ./src:/src
    networks:
      - private-net
    depends_on:
      db-service:
        condition: service_healthy # Wait for the DB to be fully ready

networks:
  private-net:
    name: private-net
    driver: bridge

volumes:
  db-data:  
